### ISSUE TITLE
R555 not starting

### ISSUE THREAD

**Issue by jphdxb** [AirTome/airtome.github.io#14] opened 2024-05-12 11:51 UTC
Hi,
Upgraded to R555 - the launch Window shows with initialisation, but at the end "Starting AirTome" window disappears and programme is not launching, also no task in Task Manager active. R554 work flawlessly.

**Comment by Chris76B** [comment] 2024-05-12 12:11
Hi, same on MacOS

**Comment by guekel** [comment] 2024-05-12 19:47
Hi, same here for my windows. I used the zip-Installation. Logfile attached.
[logfile.txt](https://github.com/AirTome/airtome.github.io/files/15287451/logfile.txt)

Console-Output:
`C:\Users\gueke\Programme\AirTome>java -jar AirTome.jar
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index 5 out of bounds for length 5
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:374)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at airtome.JView.JView_Map(JView.java:4347)
        at airtome.JView.ReDraw(JView.java:1840)
        at airtome.JView$42.changed(JView.java:1193)
        at bibliothek.gui.dock.common.intern.action.CSelectableAction$1.selectedChanged(CSelectableAction.java:62)
        at bibliothek.gui.dock.action.actions.SimpleSelectableAction.fireSelectedChanged(SimpleSelectableAction.java:159)
        at bibliothek.gui.dock.action.actions.SimpleSelectableAction.setSelected(SimpleSelectableAction.java:177)
        at bibliothek.gui.dock.common.intern.action.CSelectableAction.setSelected(CSelectableAction.java:78)
        at airtome.JView.ReDraw(JView.java:1778)
        at airtome.JSettingsfile.read(JSettingsfile.java:111)
        at airtome.JSettingsfile.read(JSettingsfile.java:18)
        at bibliothek.gui.dock.common.intern.CommonMultipleDockableFactory.layout(CommonMultipleDockableFactory.java:167)
        at bibliothek.gui.dock.common.intern.CommonMultipleDockableFactory.layout(CommonMultipleDockableFactory.java:162)
        at bibliothek.gui.dock.common.intern.CommonMultipleDockableFactory.layout(CommonMultipleDockableFactory.java:57)
        at bibliothek.gui.dock.layout.DockSituation.convert(DockSituation.java:404)
        at bibliothek.gui.dock.layout.DockSituation.convert(DockSituation.java:390)
        at bibliothek.gui.dock.layout.DockSituation.convert(DockSituation.java:390)
        at bibliothek.gui.dock.frontend.DefaultLayoutChangeStrategy.applyLayout(DefaultLayoutChangeStrategy.java:322)
        at bibliothek.gui.dock.frontend.DefaultLayoutChangeStrategy.setLayout(DefaultLayoutChangeStrategy.java:97)
        at bibliothek.gui.DockFrontend.setSetting(DockFrontend.java:1604)
        at bibliothek.gui.dock.common.intern.CDockFrontend.access$001(CDockFrontend.java:48)
        at bibliothek.gui.dock.common.intern.CDockFrontend$1.run(CDockFrontend.java:162)
        at bibliothek.gui.dock.support.mode.ModeManager.runTransaction(ModeManager.java:514)
        at bibliothek.gui.dock.facile.mode.LocationModeManager.runLayoutTransaction(LocationModeManager.java:497)
        at bibliothek.gui.dock.common.intern.CDockFrontend.setSetting(CDockFrontend.java:160)
        at bibliothek.gui.DockFrontend.readBlop(DockFrontend.java:2193)
        at bibliothek.gui.DockFrontend.readXML(DockFrontend.java:2112)
        at bibliothek.gui.DockFrontend.readXML(DockFrontend.java:2102)
        at bibliothek.gui.dock.common.CControl$9.readXML(CControl.java:893)
        at bibliothek.gui.dock.support.util.ApplicationResourceManager.readXML(ApplicationResourceManager.java:174)
        at bibliothek.gui.dock.common.CControl.readXML(CControl.java:2597)
        at bibliothek.gui.dock.common.CControl.readXML(CControl.java:2610)
        at airtome.Main.LoadWindowLayoutSettings(Main.java:404)
        at airtome.Main$3.run(Main.java:1176)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by AirTome** [comment] 2024-05-12 21:14
Unfortunately i cannot reproduce the problem at the moment.

**Comment by jphdxb** [comment] 2024-05-13 14:09
I downgraded again to R554 in the meantime, opens fine.

**Comment by Chris76B** [comment] 2024-05-13 15:07
Sure: https://github.com/AirTome/airtome.github.io/releases

Am Mo., 13. Mai 2024 um 16:09 Uhr schrieb jphdxb ***@***.***>:

**Comment by AirTome** [comment] 2024-05-14 20:16
Can you please try to use R555 in a new place. I want to check if this happens also with default settings (without flightbook, etc).

**Comment by AirTome** [comment] 2024-05-14 20:49
I think I found the problem.

**Comment by AirTome** [comment] 2024-05-14 21:00
Please try R556:
https://github.com/AirTome/airtome.github.io/releases/tag/R556

**Comment by guekel** [comment] 2024-05-15 06:07
> Please try R556: https://github.com/AirTome/airtome.github.io/releases/tag/R556

It seems for me, R556 fixed my problem. AirTome starts now, No issues at my smoke test (opening some flights).
Many thanks for quick fixing!

**Comment by jphdxb** [comment] 2024-05-15 19:13
Works for me as well, thanks for the quick fix!

**Comment by AirTome** [comment] 2024-05-16 07:15
Fixed in R556

**Closed as completed** 2024-05-16 07:15 UTC
